- type: entity
  id: BaseStationGoal
  abstract: true
  components:
    - type: StationGoal
      goals:
      - Shuttle
      - ShuttleRescue
      - Tesla
      # - SolarPanels
      - Artifacts
      - Bar
      # - Cyborgs
      - Containment
      - Botany
      - Retranslator
      - ShuttlePatrol
