- type: entity
  id: BaseStationGoal
  abstract: true
  components:
    - type: StationGoal
      goals:
      - ShuttleRescue
      # - SolarPanels
      - Artifacts
      - Bar
      - Containment
      - Botany
      - Retranslator
      - ShuttlePatrol

- type: entity
  id: BaseStationSiliconLawNTDefault
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: NTDefault
