- type: job
  id: BlueShieldOfficer
  name: job-name-blueshieldofficer
  description: job-description-blueshieldofficer
  playTimeTracker: JobBlueShieldOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 36000 # 10 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 54000 # 15 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 # 10 hrs
    - !type:AgeRequirement
      requiredAge: 25
  startingGear: BlueShieldOfficerGear
  icon: "JobIconBlueshield"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  minBankBalance: 2500
  maxBankBalance: 2900
  wageDepartment: CentralCommand
  wage: 100
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: BlueShieldOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBlueshield
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHatBeretBlueshield
    eyes: ClothingEyesGlassesBlueShield
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBlueshield
    id: BlueShieldOfficerPDA
    ears: ClothingHeadsetCommand
    pocket1: WeaponEnergyGunBlueShield
    pocket2: HandheldCrewMonitor
    belt: ClothingBeltSecurityFilled
  storage:
    back:
    - BoxSurvivalSecurity
    - Flash
