- type: job
  id: IAA
  name: job-name-iaa
  description: job-description-iaa
  playTimeTracker: JobIAA
  requirements:
    - !type:RoleTimeRequirement
      role: JobLawyer
      time: 21600 #6 hrs
    - !type:OverallPlaytimeRequirement
      time: 36000 # 10 hrs
    - !type:AgeRequirement
      requiredAge: 25
  startingGear: IAAGear
  icon: "JobIconIAA"
  supervisors: job-supervisors-magistrate
  canBeAntag: false
  access:
  - Service
  - Lawyer
  - Brig
  - Maintenance
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  minBankBalance: 550
  maxBankBalance: 750
  wageDepartment: Legal
  wage: 70

- type: startingGear
  id: IAAGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    id: IAAPDA
    ears: ClothingHeadsetLegal
    # TODO add copy of space law
  inhand:
    - BriefcaseBrownFilled
  storage:
    back:
    - BoxSurvival
    - RubberStampIAA
    - BookSpaceLaw
