################################################################################
##### General ##################################################################

[net]
port = 1212
bindto = "0.0.0.0"
log_late_msg = false

[database]
engine = "postgres"
pg_host = "{{ postgres_host }}"
pg_port = {{ postgres_port }}
pg_database = "{{ ss14setup_db_name }}"
pg_username = "{{ ss14setup_db_user }}"
pg_password = "{{ ss14setup_db_passwd }}"

[game]
hostname = "[18+][RU][MRP+] 🌌 VoidSector - Уникальный ЦентКом! 🌌"
desc = """
Приветствуем! Добро пожаловать в Пустотный сектор, место на краю галактики, где до ближайшей населенной звезды несколько сотен световых лет!

Пустотный сектор готов предоставить вам:
[🎭] Отличный уровень ролевого отыгрыша.
[📡] Отзывчивая и всегда готовая помочь администрация.
[🌌] Увеличенное количество рас, от таяран до уникальных катунианцев.
[💪] Система ношения на руках, вам больше не надо таскать кого-то за собой!
[👻] Система возрождения, теперь вам не нужно просить администратора возродить вас!
[⚒️] Локализированное меню строительства, можно не надо думать над переводом при постройке!
[🔞] ЕРП чат повышенной конфиденциальности.
[🌐] Собственная Википедия и лор сектора! История вершится вокруг вас!

Присоединяйтесь к Пустотному Сектору, полному неожиданностей и опасностей. Слава NanoTrasen!
"""
soft_max_players = 100
lobbyduration = 180
fallbackpreset = "Extended"
map_pool = "VoidMapPool"

[replay]
auto_record = true

[hub]
advertise = true
tags = "lang:ru,region:eu_e,rp:med,18+"
server_url = "ss14://37.27.103.62:1212"

[server]
rules_file = "VoidRuleset"

[console]
login_host_user = "Makot"

[admin]
see_own_notes = true
note_fresh_days = 0
message_wait_time = 1
new_player_threshold = 600
afk_time = 180.0
new_player_join_sound = true

[infolinks]
discord = "https://discord.gg/Tc5RNEWVWS"
wiki = "https://voidsector.org/"

################################################################################
##### In Game ##################################################################

[atmos]
space_wind = true
monstermos_rip_tiles = true
mmos_spacing_speed = 0.95
mmos_max_wind = 1000.0

[biomass]
easy_mode = false

[vote]
timermap = 30
map_enabled = true
restart_not_allowed_when_admin_online = true

[shuttle]
arrivals_planet = false
arrivals_returns = true
emergency_early_launch_allowed = true
emergency_dock_time = 300.0
emergency_authorize_time = 15.0
recall_turning_point = 0.1
auto_call_time = 300
auto_call_extension_time = 90

[rules]
time = 90.0

[tips]
enabled = false

[ooc]
enable_during_round = false

[looc]
enabled_crit = true

[chat]
max_announcement_length = 1024

[ic]
flavor_text = true

################################################################################
##### Discord ##################################################################

[discord]
ahelp_webhook = "{{ ahelp_void }}"
ahelp_avatar = "https://i.imgur.com/e9AMvev.png"
ahelp_footer_icon = "https://i.imgur.com/e9AMvev.png"
round_update_webhook = "{{ round_void }}"
round_end_role = "1239615123732299897"
rich_main_icon_id = "voidsector"

################################################################################
##### Metrics ##################################################################

[metrics]
enabled = true
host = "127.0.0.1"
port = 9001
runtime = false
