################################################################################
##### General ##################################################################

[net]
port = 1214
bindto = "0.0.0.0"
log_late_msg = false

[database]
engine = "sqlite"
sqlite_dbpath = "build.sqlite"

[game]
desc = "VoidSector Build"
hostname = "Пустотный Строительный"
soft_max_players = 60
lobbyenabled = false
fallbackpreset = "Sandbox"
map = "Empty"
role_timers = false

[hub]
advertise = false

[server]
rules_file = "RP_Rules.txt"
rules_header = "ui-rules-header-rp"

[console]
login_host_user = "Makot"

[admin]
see_own_notes = true
note_fresh_days = 0
message_wait_time = 1
new_player_threshold = 180
afk_time = 0.0

[accessibility]
reduced_motion = true

[physics]
grid_splitting = false

################################################################################
##### In Game ##################################################################

[atmos]
space_wind = false

[biomass]
easy_mode = false

[vote]
timermap = 30

[shuttle]
grid_fill = false
arrivals = false
emergency = false
auto_call_time = 0

[rules]
time = 0.0

[tips]
enabled = false

[ooc]
enable_during_round = true

[looc]
enabled_crit = true

[ic]
flavor_text = false
